# Generated by Django 3.2.5 on 2022-01-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_roll_number', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.CharField(max_length=100, null=True)),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('player3', models.CharField(max_length=100)),
                ('player4', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
