# Generated by Django 2.2.5 on 2022-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220119_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusQuestion',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=1000)),
                ('answer', models.CharField(max_length=120)),
                ('expiration_date', models.DateTimeField()),
                ('live_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('audiofile', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='bonus_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='bonus_level_id',
            field=models.IntegerField(default=1),
        ),
    ]
