# Generated by Django 3.2.5 on 2022-01-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220119_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='leader_name',
            new_name='leader_first_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='player1',
            new_name='leader_last_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='player2',
            new_name='leader_whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='team',
            name='freshies_only',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='open',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='player2_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player2_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player2_roll_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player3_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player3_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player3_roll_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player4_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player4_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player4_roll_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player5_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player5_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='player5_roll_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
