# Generated by Django 3.2.5 on 2022-01-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_team_id'),
        ('users', '0002_auto_20220115_1356'),
    ]

    operations = [
    ]
