# Generated by Django 3.2.5 on 2022-01-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_roll_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
