# Generated by Django 3.2.5 on 2022-01-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220119_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='freshies_only',
            field=models.BooleanField(default=1),
        ),
    ]
