# Generated by Django 3.2.5 on 2022-01-18 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220118_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_level_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
