# Generated by Django 3.2.5 on 2022-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_team_freshies_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='freshies_only',
            field=models.BooleanField(default=0),
        ),
    ]
