# Generated by Django 3.2.5 on 2022-01-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_team_current_level_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
