# Generated by Django 3.2.5 on 2022-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_team_freshies_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='freshies_only',
        ),
        migrations.RemoveField(
            model_name='team',
            name='open',
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
