# Generated by Django 2.2.5 on 2022-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220118_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='question',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
