# Generated by Django 3.2.5 on 2022-01-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220119_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
