# Generated by Django 3.2.5 on 2022-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220118_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_roll_number',
            field=models.CharField(max_length=100),
        ),
    ]
