# Generated by Django 3.2.5 on 2022-01-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220119_1319'),
        ('users', '0007_alter_team_league'),
    ]

    operations = [
    ]
