# Generated by Django 3.2.5 on 2022-01-22 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0003_auto_20220119_1319_0007_alter_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='latest_question_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 12, 40, 22, 30829)),
        ),
    ]
