# Generated by Django 3.2.5 on 2022-01-22 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_team_latest_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='latest_question_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 23, 0)),
        ),
    ]
